### PR TITLE
allow to set a class for parent div container

### LINKED ISSUE #37: Please add a way to set a class for parent div container
It would be nice to have the ability to add a class to parent div container. In Vuepress there was a class "mermaid" added by default, but there is no selector now to aid with styling.

### PR DESCRIPTION
**Pull request by dominikcz**
fixes #37

### CODE REVIEW

**Comment by emersonbottero** [comment]
hi @dominikcz , several changes where made by me since then. would you mind merge main in your code so I can merge this PR?

**Comment by dominikcz** [comment]
hi, sorry for late response, I was on vacation. Yes I'll merge your changes. Do you want me to keep my original proposal with class name as pros, or should I just stay with your solution `class="mermaid"`? Both options works for me :)

**Comment by emersonbottero** [comment]
class name as prop is good enough , mermaid been the default.

**Comment by dominikcz** [comment]
hi, I've decided to open a new PR #53 with updated version.

**Pull request closed without merging**
